USE [master]
GO

/****** Object:  Database [Avaliacao]    Script Date: 04/10/2018 22:27:16 ******/
CREATE DATABASE [Avaliacao] ON  PRIMARY 
( NAME = N'Cliente', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Cliente.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Cliente_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Cliente_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Avaliacao] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Avaliacao].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Avaliacao] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Avaliacao] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Avaliacao] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Avaliacao] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Avaliacao] SET ARITHABORT OFF 
GO

ALTER DATABASE [Avaliacao] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Avaliacao] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Avaliacao] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Avaliacao] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Avaliacao] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Avaliacao] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Avaliacao] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Avaliacao] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Avaliacao] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Avaliacao] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Avaliacao] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Avaliacao] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Avaliacao] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Avaliacao] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Avaliacao] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Avaliacao] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Avaliacao] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Avaliacao] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Avaliacao] SET  READ_WRITE 
GO

ALTER DATABASE [Avaliacao] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Avaliacao] SET  MULTI_USER 
GO

ALTER DATABASE [Avaliacao] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Avaliacao] SET DB_CHAINING OFF 
GO

